version: "3"
networks:
  order-network:
services:
  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"
    networks:
      - order-network
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "ping" ]
      interval: 5s
      timeout: 30s
      retries: 3

  gateway:
    image: nginx:latest
    volumes:
      - ./gateway_nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8000:80"
    depends_on:
      - order-service
      - stock-service
      - payment-service
    networks:
      - order-network

  order-service:
    build: ./order
    image: enriquebarba97/order-service:m1
    command: gunicorn -b 0.0.0.0:5000 app:app -w 1 --timeout 10
    restart: on-failure
    environment:
      - STOCK_URL=http://stock-service:5000
      - PAYMENT_URL=http://payment-service:5000
    env_file:
      - env/order_mongo.env
    depends_on:
      - order-db
      - rabbitmq
    networks:
      - order-network

  order-db:
    image: mongo
    restart: always
    volumes:
      - order-db-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - order-network

  stock-service:
    build: ./stock
    image: enriquebarba97/stock-service:m1
    command: gunicorn -b 0.0.0.0:5000 app:app -w 1 --timeout 10
    restart: on-failure
    env_file:
      - env/stock_mongo.env
    depends_on:
      - stock-db
      - rabbitmq
    networks:
      - order-network

  stock-db:
    image: mongo
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - stock-db-data:/data/db
    networks:
      - order-network

  payment-service:
    build: ./payment
    image: enriquebarba97/payment-service:m1
    command: gunicorn -b 0.0.0.0:5000 app:app -w 1 --timeout 10
    restart: on-failure
    env_file:
      - env/payment_mongo.env
    depends_on:
      - payment-db
      - rabbitmq
    networks:
      - order-network


  payment-db:
    image: mongo
    restart: always
    ports:
      - "27019:27017"
    volumes:
      - payment-db-data:/data/db
    networks:
      - order-network


volumes:
  order-db-data:
  stock-db-data:
  payment-db-data: