version: "3"
networks:
  order-network:
services:

  gateway:
    image: nginx:latest
    volumes:
      - ./gateway_nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8000:80"
    depends_on:
      - order-service
      - stock-service
      - payment-service
    networks:
      - order-network

  order-service:
    build: ./order
    image: order:latest
    command: gunicorn -b 0.0.0.0:5000 app:app -w 1 --timeout 10
    environment:
      - GATEWAY_URL=http://gateway:80
    env_file:
      - env/order_mongo.env
    depends_on:
      - order-db
    networks:
      - order-network

  order-db:
    image: mongo
    restart: always
    volumes:
      - order-db-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - order-network

  stock-service:
    build: ./stock
    image: stock:latest
    command: gunicorn -b 0.0.0.0:5000 app:app -w 1 --timeout 10
    environment:
      - GATEWAY_URL=http://gateway:80
    env_file:
      - env/stock_mongo.env
    depends_on:
      - stock-db
    networks:
      - order-network

  stock-db:
    image: mongo
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - stock-db-data:/data/db
    networks:
      - order-network

  payment-service:
    build: ./payment
    image: user:latest
    command: gunicorn -b 0.0.0.0:5000 app:app -w 1 --timeout 10
    environment:
      - GATEWAY_URL=http://gateway:80
    env_file:
      - env/payment_mongo.env
    depends_on:
      - payment-db
    networks:
      - order-network


  payment-db:
    image: mongo
    restart: always
    ports:
      - "27019:27017"
    volumes:
      - payment-db-data:/data/db
    networks:
      - order-network


volumes:
  order-db-data:
  stock-db-data:
  payment-db-data: