apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mongodb-ingress
spec:
  rules:
    - http:
        paths:
          - path: /orderdb
            pathType: Prefix
            backend:
              service:
                name: order-mongodb-service
                port:
                  number: 27017
          - path: /stockdb
            pathType: Prefix
            backend:
              service:
                name: stock-mongodb-service
                port:
                  number: 27017
          - path: /userdb
            pathType: Prefix
            backend:
              service:
                name: user-mongodb-service
                port:
                  number: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: dbs-access-service
spec:
  selector:
    app: mongodb-ingress
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
      nodePort: 30001

