apiVersion: v1
kind: Service
metadata:
  name: order-db
spec:
  selector:
    app: order-mongo
  ports:
    - port: 27017
      targetPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: stock-db
spec:
  selector:
    app: stock-mongo
  ports:
    - port: 27017
      targetPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: payment-db
spec:
  selector:
    app: payment-mongo
  ports:
    - port: 27017
      targetPort: 27017
