apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
data:
  order_database_url: order-mongodb-service
  stock_database_url: stock-mongodb-service
  user_database_url: user-mongodb-service
