apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-mongodb
  labels:
    app: user-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-mongodb
  template:
    metadata:
      labels:
        app: user-mongodb
    spec:
      containers:
      - name: user-mongodb
        image: mongo
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-password
---
apiVersion: v1
kind: Service
metadata:
  name: user-mongodb-service
spec:
  selector:
    app: user-mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017

