apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  type: ClusterIP
  selector:
    component: payment
  ports:
    - port: 5000
      name: http
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: payment
  template:
    metadata:
      labels:
        component: payment
    spec:
      containers:
        - name: payment
          image: enriquebarba97/payment-service:latest
          resources:
            limits:
              memory: "1Gi"
              cpu: "1"
            requests:
              memory: "1Gi"
              cpu: "1"
          command: ["gunicorn"]
          args: ["-b", "0.0.0.0:5000", "app:app"]
          ports:
            - containerPort: 5000
          env:
            - name: DB_URL
              {{ if .Values.paymentsharded.enabled}}
              value: mongodb://root:{{.Values.paymentsharded.auth.rootPassword}}@{{.Release.Name}}-paymentsharded:27017
              {{ else }}
              value: mongodb://payment-db:27017
              {{ end }}
            - name: GATEWAY_URL
              value: "http://ingress-service"
