apiVersion: v1
kind: ConfigMap
metadata:
  name: shard-init-configmap
data:
  init.js: |
    var COLLECTION = process.env.COLLECTION;

    result = db.adminCommand({
            shardCollection:"wdm." + COLLECTION,
            key: {_id: "hashed"}
    })

    printjson(result)


    printjson(sh.status())